#!/usr/bin/env bash

# absolute path of mtex directory
MTEX_ROOT="$(cd "$(dirname "$(realpath "$0")")/.." && pwd)"

# current working directory
WORK_DIR="$(pwd)"

BUILD_DIR="$WORK_DIR/.mtex-build"
PDF_DIR="$WORK_DIR/pdfs"
PDF_LOGS_DIR="$WORK_DIR/logs-pdfs"
DATE=$(date +%d-%m-%Y-%H-%M-%S)

export TEXINPUTS="$MTEX_ROOT/classes//:$MTEX_ROOT/utils//:$WORK_DIR//:$TEXINPUTS"

init() {
    mkdir -p $BUILD_DIR
    mkdir -p $PDF_DIR
    mkdir -p $PDF_LOGS_DIR
}

compile() {
    local project="$1"
    local src="$project/main.tex"
    local name=$(basename "$project")
    local outdir="$BUILD_DIR/$name"
    local outpdflogsdir="$PDF_LOGS_DIR/$name"

    cd $WORK_DIR
    echo "Worrking directory: $WORK_DIR"

    if [ ! -f $src ]; then
        echo "$src not found."
    else
        mkdir -p "$outdir" "$outpdflogsdir"
        echo "Compiling $name: $project"
        latexmk -r "$MTEX_ROOT/.latexmkrc" -pdf -jobname=$name -outdir=$outdir $src
        cp "$outdir/$name.pdf" "$outpdflogsdir/$name-$DATE.pdf"
        cp "$outdir/$name.pdf" "$PDF_DIR/$name.pdf"
        chmod 444 "$outpdflogsdir/$name-$DATE.pdf"
    fi
    
}

clean_project() {
    local project="$1"
    local name=$(basename "$project")
    local outdir="$BUILD_DIR/$name"
    local outpdfdir="$PDF_DIR/$name"

    echo "Clean $name: $project"
    rm -rf "$outdir" "$outpdfdir"
}

start_template_note() {
    local project="$1"
    local project_dir=$WORK_DIR/$project
    local tex_file="$project_dir/main.tex"

    echo "Start note project: $project_dir"

    mkdir -p $project_dir "$project_dir/figures"
    touch "$project_dir/references.bib"
    touch "$project_dir/appendix.tex"

    cat << EOF >> $tex_file
\documentclass{mtex-note}

\input{commands.tex}
\graphicspath{{figures/}}

\author{Baye Malick Gning \thanks{\texttt{\href{bmalick.gning@gmail.com}{bmalick.gning@gmail.com}}}}
\date{\today}
\title{This is the title}

\begin{document}

\maketitle

\end{document}
EOF
}

start_template_report() {
    local project="$1"
    local project_dir=$WORK_DIR/$project
    local tex_file="$project_dir/main.tex"

    echo "Start report project: $project_dir"

    mkdir -p $project_dir "$project_dir/figures"
    touch "$project_dir/references.bib"
    touch "$project_dir/appendix.tex"

    cat << EOF >> $tex_file
\documentclass{mtex-note}

\input{commands.tex}
\graphicspath{{figures/}}

\author{Baye Malick Gning \thanks{\texttt{\href{bmalick.gning@gmail.com}{bmalick.gning@gmail.com}}}}
\date{\today}
\title{This is the title}

\begin{document}

\maketitle

\end{document}
EOF
}

read_pdf() {
    local project="$1"
    local name=$(basename "$project")
    local outpdf="$PDF_DIR/$name.pdf"
    echo "Read $name: $project"
    if [ -f $outpdf ]; then
        open $outpdf
    else
        echo "$name does not exist."
    fi
}

# mTeX CLI tool
# Author: Baye Malick Gning
#

init

case "$1" in 

    start)
        project="$2"
        echo "Create empty project: $WORK_DIR/$project"
        mkdir -p $WORK_DIR/$project
        echo "Project directory created at: $WORK_DIR/$project"
    ;;

    start-note)
        start_template_note $2
    ;;

    start-report)
        start_template_report $2
    ;;

    build)
        project=$2
        compile $2
    ;;

    clean)
        clean_project $2
    ;;

    read)
        read_pdf $2
    ;;

    *)
        echo "mtex helper"
        echo "Usage:"
        echo "  mtex start <project-name>"
        echo "  mtex build <project-name>"
        echo "  mtex clean <project-name>"

esac
